# pytorch是什么？
- pytorch与NumPy的ndarray非常类似，但是可以在GPUs上运算的数据结构，这个有点像spark的RDD
- 是一个深度学习的框架，有非常好的扩展性和速度

In [1]:
from __future__ import print_function
import torch
import numpy as np
print(torch.__version__)

1.2.0


# Tensors & numpy

In [2]:
type(torch.empty(3,3))

torch.Tensor

In [3]:
# construct a 5×3 matrix,uninitialized.
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
np.empty((5,3))

array([[1.05895010e-153, 1.67646296e+243, 4.97572663e-003],
       [8.32980125e+151, 7.94094759e+068, 6.16778845e+223],
       [1.16294398e-012, 2.88718352e+170, 4.27243065e+180],
       [7.92521264e+068, 4.79099818e+276, 9.62006167e+228],
       [7.09806742e+194, 4.23275986e+175, 2.51719506e+180]])

In [5]:
type(x)

torch.Tensor

In [6]:
# construct a randomly initialized matrix,from uniform distribution
x = torch.rand(5,3)
print(x)
print('-------')
print(x.shape)

tensor([[0.3780, 0.3891, 0.5887],
        [0.0880, 0.5687, 0.9153],
        [0.2279, 0.5821, 0.8669],
        [0.7691, 0.9298, 0.6357],
        [0.3629, 0.5329, 0.0762]])
-------
torch.Size([5, 3])


In [7]:
# uniform distribution
np.random.rand(5,3)

array([[0.8064486 , 0.37734207, 0.65724008],
       [0.48079196, 0.84268304, 0.26703259],
       [0.29325114, 0.69661726, 0.80047551],
       [0.47440341, 0.82637394, 0.73145739],
       [0.68653793, 0.83660573, 0.80287691]])

In [8]:
# construc a matrix filled zeros and of dtype long:
x = torch.ones(5,3,dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [48]:
torch.ones(4,3,dtype=torch.long).dtype

torch.int64

In [45]:
torch.ones(4,3).dtype

torch.float32

In [9]:
np.ones((5,3),dtype=np.long)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
torch.Tensor(range(10))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
# construct a tensor from data
x = torch.Tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.rand_like(x,dtype=torch.float) # result has the same size
print(x)

tensor([[0.8776, 0.7383, 0.9574],
        [0.1201, 0.0807, 0.5940],
        [0.1977, 0.4132, 0.3187],
        [0.3378, 0.9825, 0.9925],
        [0.9710, 0.9761, 0.4349]])


- 获取size

In [55]:
x.size()[0]

4

# operations

In [13]:
x

tensor([[0.8776, 0.7383, 0.9574],
        [0.1201, 0.0807, 0.5940],
        [0.1977, 0.4132, 0.3187],
        [0.3378, 0.9825, 0.9925],
        [0.9710, 0.9761, 0.4349]])

In [14]:
y = torch.rand(5,3)
print(x + y)

tensor([[0.8922, 1.3503, 1.7411],
        [0.2838, 0.1829, 1.3977],
        [0.7698, 0.5655, 0.9071],
        [0.6274, 1.4900, 1.1579],
        [1.2715, 1.6031, 1.1683]])


In [15]:
print(torch.add(x,y))

tensor([[0.8922, 1.3503, 1.7411],
        [0.2838, 0.1829, 1.3977],
        [0.7698, 0.5655, 0.9071],
        [0.6274, 1.4900, 1.1579],
        [1.2715, 1.6031, 1.1683]])


In [16]:
# providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.8922, 1.3503, 1.7411],
        [0.2838, 0.1829, 1.3977],
        [0.7698, 0.5655, 0.9071],
        [0.6274, 1.4900, 1.1579],
        [1.2715, 1.6031, 1.1683]])


In [17]:
x

tensor([[0.8776, 0.7383, 0.9574],
        [0.1201, 0.0807, 0.5940],
        [0.1977, 0.4132, 0.3187],
        [0.3378, 0.9825, 0.9925],
        [0.9710, 0.9761, 0.4349]])

In [18]:
x.add_(y)

tensor([[0.8922, 1.3503, 1.7411],
        [0.2838, 0.1829, 1.3977],
        [0.7698, 0.5655, 0.9071],
        [0.6274, 1.4900, 1.1579],
        [1.2715, 1.6031, 1.1683]])

In [19]:
x

tensor([[0.8922, 1.3503, 1.7411],
        [0.2838, 0.1829, 1.3977],
        [0.7698, 0.5655, 0.9071],
        [0.6274, 1.4900, 1.1579],
        [1.2715, 1.6031, 1.1683]])

- add_ in-place
- 以_结尾的操作都是原位操作

In [20]:
print(x[:,1])

tensor([1.3503, 0.1829, 0.5655, 1.4900, 1.6031])


# resize/reshape view

In [21]:
x = torch.randn(4,4)

In [22]:
x.size()

torch.Size([4, 4])

In [23]:
x

tensor([[ 0.5410,  2.2992,  1.8898, -1.5068],
        [-0.0453,  1.8983, -1.7788, -1.3576],
        [ 0.2294, -0.4796,  0.1628,  0.3109],
        [ 0.0751,  1.9649, -0.9614, -0.9686]])

In [24]:
y = x.view(16)

In [25]:
y.size()

torch.Size([16])

In [26]:
y

tensor([ 0.5410,  2.2992,  1.8898, -1.5068, -0.0453,  1.8983, -1.7788, -1.3576,
         0.2294, -0.4796,  0.1628,  0.3109,  0.0751,  1.9649, -0.9614, -0.9686])

In [27]:
z = x.view(-1,8)

In [28]:
z

tensor([[ 0.5410,  2.2992,  1.8898, -1.5068, -0.0453,  1.8983, -1.7788, -1.3576],
        [ 0.2294, -0.4796,  0.1628,  0.3109,  0.0751,  1.9649, -0.9614, -0.9686]])

In [29]:
x.reshape(-1,8)

tensor([[ 0.5410,  2.2992,  1.8898, -1.5068, -0.0453,  1.8983, -1.7788, -1.3576],
        [ 0.2294, -0.4796,  0.1628,  0.3109,  0.0751,  1.9649, -0.9614, -0.9686]])

In [30]:
# 过时了
x.resize(2,8)

/Users/renal/anaconda3/lib/python3.7/site-packages/torch/tensor.py:293: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[ 0.5410,  2.2992,  1.8898, -1.5068, -0.0453,  1.8983, -1.7788, -1.3576],
        [ 0.2294, -0.4796,  0.1628,  0.3109,  0.0751,  1.9649, -0.9614, -0.9686]])

In [31]:
torch.get_num_threads()

1

# torch和numpy共享内存（如果是基于cpu的话），如果一个变化另一个也变化，而且两者可以相互转化

## convert a torch Tensor to numpy

In [32]:
a = torch.ones(5)

In [33]:
b = a.numpy()

In [34]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [36]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

## convert a numpy to torch tensor 两种转换方式
- 从数组中直接初始化一个torch.Tensor()对象
- 使用from_numpy方法

In [37]:
a = np.ones(5)

In [38]:
a

array([1., 1., 1., 1., 1.])

In [39]:
b = torch.Tensor(a)

In [40]:
b = torch.from_numpy(a)

In [41]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [56]:
a

array([1., 1., 1., 1., 1.])

In [59]:
c = torch.Tensor(a)

tensor([1., 1., 1., 1., 1.])

In [60]:
torch.from_numpy(a)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)