In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
y.grad_fn

In [7]:
z = y * y * 3

In [8]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [9]:
out  = z.mean()

In [10]:
out

tensor(27., grad_fn=<MeanBackward0>)

# Gradient

In [11]:
out.backward()

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# Jacobian matrix

In [13]:
x = torch.randn(3,requires_grad=True)

In [14]:
x

tensor([-0.8077,  0.4869,  0.2544], requires_grad=True)

In [15]:
y = x * 2

In [16]:
y

tensor([-1.6153,  0.9738,  0.5089], grad_fn=<MulBackward0>)

In [17]:
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-827.0466,  498.5775,  260.5338], grad_fn=<MulBackward0>)


In [18]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)

In [19]:
v

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])

In [20]:
y.backward(v)

In [21]:
print(y)

tensor([-827.0466,  498.5775,  260.5338], grad_fn=<MulBackward0>)


In [22]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


## stop autograd

In [23]:
print(x.requires_grad)

True


In [24]:
print((x**2).requires_grad)

True


In [25]:
with torch.no_grad():
    print((x**2).requires_grad)

False
